apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
spec:
  selector:
    app: ingestion-service
  ports:
    - port: 8003
      targetPort: 8003
  type: ClusterIP   # internal only — nginx/Ingress exposes it externally
