apiVersion: v1
kind: Secret
metadata:
  name: carrental-secrets
type: Opaque
data:
  # Values must be base64 encoded. To encode: echo -n "yourvalue" | base64
  # "postgres" in base64
  DB_USER: cG9zdGdyZXM=
  # "Ayush@2002" in base64
  DB_PASSWORD: QXl1c2hAMjAwMg==
