apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do sleep 2; done']
        - name: wait-for-kafka
          image: busybox
          command: ['sh', '-c', 'until nc -z kafka 9092; do echo "waiting for kafka..."; sleep 2; done; echo "Kafka port open — waiting for broker ready..."; sleep 10']
      containers:
        - name: ticket-service
          image: carrental-ticket-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:Ayush%402002@postgres/carrental"
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: carrental-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_GROUP_ID
              value: "ticket-service-group"
