apiVersion: v1
kind: Service
metadata:
  name: ticket-service
spec:
  selector:
    app: ticket-service
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP          # Ingress will expose this externally — not this Service
